package com.example.jimmer.entity;

import org.babyfish.jimmer.sql.Entity;
import org.babyfish.jimmer.sql.Id;

import java.math.BigDecimal;

/**
 * An immutable Jimmer entity with BookDraft and its Builder generated by the annotation processor.
 */
@Entity
public interface Book {

    @Id
    long id();

    String name();

    BigDecimal price();
}
